apiVersion: v1  
kind: Pod  
metadata:  
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:  
  containers:  
    - name: nginx
      image: nginx:1.27.2
      volumeMounts:  
        - mountPath: "/usr/share/nginx/html"
          name: test-pv
  volumes:  
    - name: test-pv
      persistentVolumeClaim:  
        claimName: test-pvc
