apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: test-pvc  
spec:  
  storageClassName: hostpath-provisioner 
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 1Gi