apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: 80-tcp
    port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginx
  type: LoadBalancer