# This example has init containers that require two services to exist before 
# allowing the main container(s) to launch.
# 
# The required services are in the services-init-requires.yaml file in this folder.
#
# You can also experiement with creating just the first service and not the second 
# to see that initContainers requires each to complete successfully in order before
# moving onto the containers from the initContainers

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: mirror.gcr.io/busybox:1.37.0
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: mirror.gcr.io/busybox:1.37.0
    command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
  - name: init-mydb
    image: mirror.gcr.io/busybox:1.37.0
    command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]