prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
  prometheus:
    monitor:
      attachMetadata:
        node: true
      relabelings:
      - sourceLabels:
        - __meta_kubernetes_endpoint_node_name
        targetLabel: node
        action: replace
        regex: (.+)
        replacement: ${1}
prometheus:
  service:
    type: LoadBalancer
grafana:
  image:
    registry: mirror.gcr.io
  service:
    type: LoadBalancer
    port: 3000
kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings: null
crds:
  upgradeJob:
    enabled: true
    image:
      busybox:
        registry: mirror.gcr.io