apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: legacy-ingress-gateway

resources:
- probe-test-app-deployment.yaml
- probe-test-app-service.yaml
- gateway.yaml
- virtualservice.yaml