apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: generate-load-app
  labels:
    app.kubernetes.io/name: generate-load-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: generate-load-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generate-load-app
    spec:
      containers:
        - name: generate-load-app
          image: busybox:1.37.0
          command: ["/bin/sh"]
          args: ["-c", "while sleep 0.01; do wget -q -O- http://probe-test-app:8000; done"]