apiVersion: v1
kind: Pod
metadata:
  name: probe-test-app
  labels:
    app.kubernetes.io/name: probe-test-app
spec:
  containers:
  - name: probe-test-app
    image: jasonumiker/probe-test-app:latest
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 50m
        memory: 52Mi
