apiVersion: v1
kind: Secret
metadata:
  name: erlang-cookie
type: generic
stringData:
  cookie: super-secret-erlang-cookie
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin
type: generic
stringData:
  user: admin
  pass: admin