apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo-rollouts-demo

resources:
- bluegreen-service.yaml
- bluegreen-gateway.yaml
- bluegreen-preview-service.yaml
- bluegreen-preview-gateway.yaml
- success-rate-analysis.yaml
- bluegreen-rollout-manual.yaml

