apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publish
spec:
  template:
    spec:
      containers:
        - name: rabbitmq-client
          image: ghcr.io/kedacore/rabbitmq-client:v1.0
          env:
          - name: rabbitmq_host
            valueFrom:
              secretKeyRef:
                name: rabbitmq-consumer-secret
                key: host
          command:
            [
              "send",
              $(rabbitmq_host),
              "300",
            ]
      restartPolicy: Never
  backoffLimit: 4