apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: probe-test-app
spec:
  project: default
  source:
    repoURL: https://github.com/jasonumiker/kubernetes-training
    targetRevision: HEAD
    path: probe-test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas