resources:
- ../base
namePrefix: stg-

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-nginx
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
