apiVersion: v1
kind: Pod
metadata:
  name: memory-stressor
spec:
  containers:
  - name: memory-stressor
    image: mirror.gcr.io/polinux/stress:1.0.4
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]